import globals from "globals";
import pluginJs from "@eslint/js";


export default [
  {
    files: ["**/*.js"],
    languageOptions: {
      sourceType: "commonjs",
      globals: {
        ...globals.browser,
        AVE_IS_THIS_SESSION_MASTER: 'writable',
        DB_HANDLER: 'writable',
        SETTINGS: 'writable',
        AVE_VERSION: 'readonly',
        AVE_TITLE: 'readonly',
        SECONDS_PER_DAY: 'readonly',
        SECONDS_PER_WEEK: 'readonly',
        SITE_IS_VINE: 'readonly',
        SITE_IS_SHOPPING: 'readonly',
        AVE_SESSION_ID: 'readonly',
        INIT_AUTO_SCAN: 'readonly',
        AUTO_SCAN_IS_RUNNING: 'readonly',
        AUTO_SCAN_PAGE_CURRENT: 'readonly',
        AUTO_SCAN_PAGE_MAX: 'readonly',
        PAGE_LOAD_TIMESTAMP: 'readonly',
        DATABASE_NAME: 'readonly',
        DATABASE_OBJECT_STORE_NAME: 'readonly',
        DATABASE_VERSION: 'readonly',
        Product: 'readonly',
        SETTINGS_USERCONFIG_DEFINES: 'readonly',
        SETTINGS_DEFAULT: 'readonly',
        GM_info: 'readonly',
        GM_getValue: 'readonly',
        GM_setValue: 'readonly',
        GM: 'readonly',
        "GM.getValue": 'readonly',
        "GM.setValue": 'readonly',
        "GM.xmlHttpRequest": 'readonly',
        unsafeWindow: 'readonly',
        ave_eventhandler: 'readonly',
        loadSettings: 'readonly',
        saveSettings: 'readonly',
        unixTimeStamp: 'readonly',
        toUnixTimestamp: 'readonly',
        toTimestamp: 'readonly',
        waitForHtmlElmement: 'readonly',
        waitForHtmlElementPromise: 'readonly',
        findActiveMenuButton: 'readonly',
        delay: 'readonly',
        fastStyleChanges: 'readonly',
        generateSessionID: 'readonly',
        addBranding: 'readonly',
        saveAs: 'readonly',
        // Browser built-ins not already in globals.browser should be here if needed
        // But the ones listed like localStorage, console, etc. are typically in globals.browser
        // Explicitly listing them again if not covered or for clarity:
        localStorage: 'readonly',
        console: 'readonly',
        document: 'readonly',
        window: 'readonly',
        Notification: 'readonly',
        DOMParser: 'readonly',
        URLSearchParams: 'readonly',
        Blob: 'readonly',
        FileReader: 'readonly',
        indexedDB: 'readonly',
        Date: 'readonly',
        Math: 'readonly',
        Number: 'readonly',
        String: 'readonly',
        Object: 'readonly',
        Array: 'readonly',
        Promise: 'readonly',
        Event: 'readonly',
        MutationObserver: 'readonly',
        requestAnimationFrame: 'readonly',
        clearTimeout: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        isNaN: 'readonly',
        parseInt: 'readonly',
        parseFloat: 'readonly',
        decodeURIComponent: 'readonly',
        encodeURIComponent: 'readonly',
        Intl: 'readonly',
        performance: 'readonly',
        navigator: 'readonly',
        PAGETYPE: 'readonly',
        injectDarkMode: 'readonly',
        handleInfiniteScroll: 'readonly',
        getUrlParameter: 'readonly',
        detectCurrentPageType: 'readonly',
        parseTileData: 'readonly',
        reloadPageWithSubpageTarget: 'readonly',
        addLeftSideButtons: 'readonly',
        markAllCurrentSiteProductsAsSeen: 'readonly',
        markAllCurrentDatabaseProductsAsSeen: 'readonly',
        createButton: 'readonly',
        createTileFromProduct: 'readonly',
        createFavStarElement: 'readonly',
        createFirstSeenElement: 'readonly',
        createTimeSeenElement: 'readonly',
        timeAgo: 'readonly',
        createShareElement: 'readonly',
        shareEventHandlerClick: 'readonly',
        createTaxInfoElement: 'readonly',
        insertHtmlElementAfter: 'readonly',
        createProductSite: 'readonly',
        createInfiniteScrollSite: 'readonly',
        appendInfiniteScrollTiles: 'readonly',
        createNewSite: 'readonly',
        getTilesFromURL: 'readonly',
        btnEventhandlerClick: 'readonly',
        favStarEventhandlerClick: 'readonly',
        updateTileStyle: 'readonly',
        initTileEventHandlers: 'readonly',
        addTileEventhandlers: 'readonly',
        completeDelayedInit: 'readonly',
        showAutoScanScreen: 'readonly',
        updateAutoScanScreenText: 'readonly',
        addAveSettingsTab: 'readonly',
        addAVESettingsMenu: 'readonly',
        createSettingsMenuElement: 'readonly',
        createSettingsKeywordsTableElement: 'readonly',
        addOverlays: 'readonly',
        componentToHex: 'readonly',
        rgbToHex: 'readonly',
        rgbaToHex: 'readonly',
        colorToHex: 'readonly',
        addDBCleaningSymbol: 'readonly',
        addDBLoadingSymbol: 'readonly',
        addLoadingSymbol: 'readonly',
        getPageinationData: 'readonly',
        cleanUpDatabase: 'readonly',
        exportDatabase: 'readonly',
        importDatabase: 'readonly',
        readFile: 'readonly',
        initBackgroundScan: 'readonly',
        backGroundTileScanner: 'readonly',
        showBackgroundScanScreen: 'readonly',
        updateBackgroundScanScreenText: 'readonly',
        startAutoScan: 'readonly',
        handleAutoScan: 'readonly',
        stickElementToTopScrollEVhandler: 'readonly',
        updateNewProductsBtn: 'readonly',
        desktopNotifikation: 'readonly',
        createNavButton: 'readonly',
        addStyleToTile: 'readonly',
        requestProductDetails: 'readonly',
        init: 'readonly',
        sort_by_key: 'readonly',
      }
    }
  },
  pluginJs.configs.recommended,
];